AWSTemplateFormatVersion: "2010-09-09"
Description: GCP to AWS
Parameters:
  BucketName:
    Description: Name of the S3 bucket
    Type: String
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref BucketName
        S3Key: function.zip
      Description: GCP to AWS function
      FunctionName: GCPtoAWS
      Handler: list_buckets.lambda_handler
      MemorySize: 128
      Role: !GetAtt ExecutionRole.Arn
      Runtime: python3.7
      Timeout: 5
      Tags:
        -
          Key: "Demo"
          Value: "true"
        -
          Key: "Project"
          Value: "GCP to AWS file transfer"
